openapi: 3.0.3
info:
  title: OpenAPI schema for Prometheus MSTeams template .
components:
  schemas:
    variables:
      type: object
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: Namespace where MSTeams will be installed.
          default: prometheus-system
          x-walrus-ui:
            group: Basic
            order: 1
        helm_release_name:
          title: Helm Release Name
          type: string
          description: Name for the MSTeams Helm release.
          default: prometheus-msteams
          x-walrus-ui:
            group: Basic
            order: 2
        helm_release_version:
          title: Helm Release Version
          type: string
          description: Version of the MSTeams Helm chart.
          default: 1.3.4
          x-walrus-ui:
            group: Basic
            order: 3
        alert_webhook:
          title: Alert Webhook
          type: string
          description: Webhook URL for Prometheus alerts to MS Teams
          default: https://new.webhook.url/...
          x-walrus-ui:
            group: Basic
            order: 4
        alert_channel:
          title: Alert Channel
          type: string
          description: Channel name for Prometheus alerts to MS Teams
          default: alerts_dev
          x-walrus-ui:
            group: Basic
            order: 5
        service_monitor:
          title: Service Monitor
          type: boolean
          description: Enable or disable the service monitor
          default: true
          x-walrus-ui:
            group: Basic
            order: 6
        release_label:
          title: Release Label
          type: string
          description: Label used for the Prometheus release
          default: prometheus
          x-walrus-ui:
            group: Basic
            order: 7
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for the Prometheus msteams Helm
            release.
          default:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 1m
              memory: 8Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
      x-walrus-ui:
        groupOrder:
        - Basic
